src/pages/login/index.html
src/styles/abstracts/_variables.scss
src/styles/pages/_cart.scss
src/styles/pages/_login.scss
src/styles/themes/_theme.scss
vite.config.js

| 완성 이미지/GIF |
|![image](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/d37edaaf-24bd-4802-900d-d153a31b7347)|
- 로그인 페이지 퍼블리싱
- 공통 스타일 수정
- vite 설정 수정

Feat/kim/#2: 로그인 페이지 퍼블리싱 완료

---

index.html
src/styles/pages/_main.scss

| 완성 이미지/GIF |
|       ![screencapture-localhost-5173-2024-01-07-14_25_16](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/0d68ffaf-e3d9-406d-97bd-70d78dce3afb)  |
- 메인 페이지에 푸터 추가
- 메인 페이지 mixin으로 변경할 수 있는 부분까지 변경

Modifiy(feat/ryu/#10): 메인 페이지 푸터 추가 및 mixin으로 변경

---

index.html
main.js
package-lock.json
package.json
src/styles/pages/_main.scss

| 완성 이미지/GIF |
|         ![화면 기록 2024-01-08 오후 4 49 00](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/18567bd9-b650-4429-a009-83adc1b955df)        |
- swiperjs 설치 -> `npm i` 해야합니다.
- 3초가 흐르면 다음 광고로 넘어가고 화살표를 클릭할 경우 바로 다음으로 이동한다.
- 마지막 광고일 경우 처음 광고로, 처음 광고일 경우 마지막 광고로 이동한다.

Feat/ryu/#18: 메인 페이지 배너 스와이퍼 완성

---

src/lib/utils/delay.js

| 완성 이미지/GIF |
|![bugfix#22](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/9098b9f4-4c82-4452-be6d-49b59f61bac8)|
- 불필요한 소스코드 제거
- 불필요한 주석 제거

bugfix(feat/sang/#22): 불필요한 코드 및 주석 제거

---

src/pages/cart/index.html
src/styles/pages/_cart.scss

| 완성 이미지/GIF |
|         ![스크린샷 2024-01-09 오전 9 25 07](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/85b6c66d-fcd2-4a68-85c9-bd045b9c2fe1)        |
- `<main>` 전체 너비 변경
- 잘못된 믹스인 수정

Modifiy(feat/ryu/#28): 장바구니 페이지 수정

---

src/pages/login/index.html
src/pages/login/login.js
src/styles/pages/_login.scss

| 완성 이미지/GIF |
|![image](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/b9492068-e33b-4c02-892f-7f0918ce700f)|
- html 헤더 및 푸터 영역 수정본 적용
- login.js 생성 및 style.scss 경로 연결
- html 영역 main.js -> login.js로 경로 수정
- scss 파일 내 pure css 코드 믹스인 사용 수정

feat(feat/kim/#25): 로그인 페이지 html/css 일부 수정 및 자바스크립트 파일 생성

---

src/pages/products/index.html
src/styles/layout/_header.scss

| 완성 이미지/GIF |
|![feat#29 header_dropdown](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/875ed931-f069-462c-a94a-292fa518d962)|
- 헤더 카테고리 드롭다운 메뉴 구현

feat(feat/sang/#29): 카테고리 드롭다운 메뉴 구현

---

index.html
src/styles/pages/_main.scss

| 완성 이미지/GIF |
|       ![화면 기록 2024-01-09 오후 2 17 40](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/e40a2cfc-47f4-42aa-9ad4-0134eb327599)          |
- 배너 크기 고정적으로 수정
- 배너 버튼을 키보드 키로 접근 가능하도록 수정
- 상품 클릭 및 키보드로 접근 시 디테일 페이지로 이동

modify(feat/ryu/#36): 메인 페이지 키보드 키로 동장 및 배너 크기 수정

---

src/pages/login/index.html
src/pages/register/index.html
src/styles/pages/_login.scss
src/styles/pages/_register.scss

| 완성 이미지/GIF |
|![회원가입 레이아웃 무너짐](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/3e23b97d-2a46-4bb2-805e-1898b00913db)
**이슈 원인 : 마크업 클래스가 form-wrapper와 같이 element 지정 없이 포괄적으로 지정하여 크롬 확장 프로그램과 충돌 발생**
- 로그인 및 회원가입 페이지 html 마크업 클래스명 수정
- scss 수정된 클래스명으로 변경

fix(feat/kim/#34): 로그인, 회원가입 페이지 input 필드 레이아웃 무너짐 해결

---

src/pages/register/index.html
src/styles/pages/_register.scss

| 완성 이미지/GIF |
|![-super-market-Chrome2024-01-0919-10-10-ezgif com-video-to-gif-converter](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/0745ebba-1715-4a2c-b1cd-b44236ed2418)|
- 회원가입 페이지 라디오 및 체크박스 키보드 접근 가능하게 수정
- scss 파일 pure css로 작성된 부분 믹스인 사용으로 수정
- 아이디 및 비밀번호 입력란에 maxlength="16" minlength="6" attribute 추가

modify(feat/kim/#41): 회원가입 페이지 체크박스 키보드 접근 가능하게 수정 및 scss 믹스인 사용

---

index.html
main.js
src/styles/pages/_main.scss

| 완성 이미지/GIF |
|         ![화면 기록 2024-01-09 오후 4 33 17](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/c2eb56f8-5939-47f3-b99c-5dc3697bb3ae)        |
- '닫기' 버튼을 눌렀을 경우, 팝업이 바로 닫아집니다.
- '오늘 하루 안 보기' 버튼을 눌렀을 경우, 오늘 날짜("2024-01-09")를 로컬 스토리지에 넣고 팝업을 닫습니다.
- '오늘 하루 안 보기' 버튼을 누르고 새로고침을 하면
- 로컬 스토리지에 저장된 날짜와 버튼을 누른 날짜를 비교하고 같다면 팝업이 안 나타납니다.
- 만약 날짜가 다르다면 팝업이 나타나고, 이때 또 버튼을 누른다면 로컬 스토리지의 날짜가 변합니다.
```jsx
const closePopup = () => {
removeClass('.popup', 'is--active');
};
getNode('.popup .close').addEventListener('click', handleClosePopupButton);
getNode('.popup .close').addEventListener('click', closePopup);
```
- `handleClosePopupButton` 함수와 `closePopup` 함수의 내용이 같아 `handleClosePopupButton` 함수를 제거할지 고민중입니다.
```html
<button class="watch-today" …
```

feat(feat/ryu/#32): 메인 페이지 팝업 완료

---

index.html
main.js
src/styles/pages/_main.scss

| 이전 | 이후(큰 화면) | 이후(좁은 화면) | 
| --------------- | --------------- | --------------- |
|     ![295148886-074f4a6d-7e78-493d-bedb-7ede6e0d3fd5](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/8309c8ea-c3af-4a03-9d5b-5fe0c60cc23c)            | ![스크린샷 2024-01-09 오후 8 13 03](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/46201ef1-3cf9-425f-a553-cc5f33c20c6a) |  ![스크린샷 2024-01-09 오후 8 12 58](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/e5393f59-235d-4576-b8d0-fd21b533ff0e) |
- 메인 페이지 배너 위치 수정

modify(feat/ryu/#45): 메인페이지 배너 스타일, 위치 수정

---

index.html
main.js
src/styles/components/_productCard.scss
src/styles/pages/_main.scss

| 완성 이미지/GIF |
|       ![화면 기록 2024-01-10 오전 10 45 51](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/0f8a4b47-8722-4b7e-82e5-a74eedcda6d7)           |
- 메인페이지 헤더 변경사항 추가
- 상품카드를 mixin을 사용하는 방식으로 수정
- 상품 리스트 스와이퍼
- 스와이퍼 함수 생성해서 공통부분 제거

feat(feat/ryu/#48): 메인페이지 상품 스와이퍼

---

src/pages/cart/index.html
src/pages/cart/index.js

| 완성 이미지/GIF |
|![feat#55 cart-header](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/c1cf245d-e72f-4c7e-af70-2d4af0db1172)|
- 장바구니 페이지 헤더 최신화

feat(feat/sang/#55): 장바구니 헤더 활성화 fixHeader에서 initHeader 로 변경

---

src/pages/products/index.html
src/pages/products/index.js
src/styles/pages/_products.scss

| 완성 이미지/GIF |
|![feat#51 products-nav](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/2ce85d28-6c77-404c-956c-ff092021b156)|
- 네비게이션 메뉴 펼치기
- 네비게이션 메뉴 펼칠 시 우측 이미지 마이크로 애니메이션 적용
- 각 카테고리 체크박스 클릭 시 카운트 표시

Feat/sang/#51: 네비게이션 메뉴 펼치기, 체크박스 클릭 시 카운트 표시 및 초기화 기능 구현

---

src/pages/detail/index.html
src/pages/detail/index.js
src/styles/pages/_detail.scss

1. handleCount 함수
- -,+ 버튼을 클릭하면 count를 변경할수 있는 함수 구현
- 수량이 1보다 작을경우 alert를 통해서 수량을 1개 이상 담을 수 있도록 함
2. showTotalPrice 함수
- 옵션에 있는 가격에 count 수량을 곱해주고, 이를 총상품금액에 표시되도록 함

Feat/kina/#43: 상품 주문 갯수 및 갯수에 따른 금액 계산 후 표시 기능

---

src/pages/products/index.html
src/pages/products/index.js
src/styles/layout/_header.scss
src/styles/pages/_products.scss

| 완성 이미지/GIF |
|![feat#59 products-nav](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/7211757c-007d-49b4-9588-0ef2c5196f41)|
- 체크박스 클릭 시 해당 항목 화면 중앙에 표시하는 기능 구현
- 화면 중앙에 표시된 항목을 지우는 기능 구현
- 체크된 항목이 있는 영역의 네비게이션 영역을 펼침 상태로 로드하는 기능 구현
- 체크된 항목이 있는 영역에 체크된 항목의 갯수를 표시하는 기능 구현
- 해당 pr이 merge 된 이후 header 붙여넣기 필요
- 기능 구현 과정에서 발견된 버그 수정 : 드롭다운 메뉴가 페이지 로드 전 마우스 위치에 따라 나타나는 문제 수정

Feat/sang/#59: 네비게이션 체크박스 관련 기능 구현

---

src/pages/register/index.html
src/pages/register/index.js
src/styles/pages/_register.scss

| 완성 이미지/GIF |
|![Animation](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/d5849058-c547-4739-9d1d-e7f10ab23dde)|
- 별 표시된 필수 입력 필드(아이디, 비밀번호, 비밀번호 확인, 이름, 이메일, 휴대폰) 조건 문구 출력

feat(feat/kim/#57): 회원가입 페이지 필수 입력 필드 조건 문구 출력

---

src/pages/login/index.html
src/pages/login/index.js
src/styles/pages/_login.scss

| 완성 이미지/GIF |
|![Animation](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/22bc6ed1-5152-4c81-8b77-0126fd5aeb52)|
- 로그인 페이지 아이디, 비밀번호 조건 문구 출력
- sr-only 레이블 추가

feat(feat/kim/#66): 로그인 페이지 아이디, 비밀번호 조건 문구 출력 및 sr-only 레이블 추가

---

index.html
main.js
src/lib/components/index.js
src/lib/components/recentBar.js
src/styles/components/_recentBar.scss

| 완성 이미지/GIF |
|        ![화면 기록 2024-01-11 오후 3 29 01](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/4e228661-a4a1-4c0f-bd52-e8566e7277f3)         |
- 최근 본 상품이 없다면 안보이게, 있다면 보이게 설정
- 상품 클릭 후 디테일 페이지로 이동했던 상품이라면 최근 본 상품에 추가
- 이전에 봤던 상품을 또 봤다면 최근 본 상품의 상단으로 이동
- `<`, `>` 버튼 클릭 시 상품이 하나씩 스크롤  → `swiperjs` 사용

feat(feat/ryu/#64): 최근 본 상품

---

src/pages/products/index.html
src/pages/products/index.js

| 완성 이미지/GIF |
|![feat#71 category-dynamic-create](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/d9c55272-7e8f-4ff0-b4b3-4e52f6e1d152)|
- 카테고리 메뉴 템플릿으로 생성
- db와 통신하며 카테고리 메뉴를 가져오는 속도가 느려지는 문제 개선
- localStorage 체크 후 카테고리 데이터가 없으면 받아서 저장하고, localStorage를 활용해 메뉴 렌더링

Feat/sang/#71: 카테고리 목록 동적 렌더링

---

src/lib/components/checkbox.js
src/pages/register/index.html
src/pages/register/index.js
src/styles/pages/_register.scss

| 완성 이미지/GIF |
|![Animationd](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/7e4b27f0-512a-41e7-82e2-73734e234397)|
- 필수 입력란 validation 모두 통과 및 필수 동의란까지 모두 체크 완료되어야만 회원가입 버튼 활성화

feat(feat/kim/#70): 필수 입력란 입력 완료 및 필수 동의 체크란까지 모두 체크 완료 시 회원가입 버튼 활성화 기능 추가

---

src/lib/components/checkbox.js
src/lib/components/index.js
src/pages/register/index.js

| 완성 이미지/GIF |
|                 |
- changeAllCheck 모듈 레퍼런스 에러 해결

fix(feat/kim/#78): changeAllCheck 모듈 레퍼런스 에러 해결

---

src/pages/detail/index.html
src/styles/pages/_detail.scss

| 완성 이미지/GIF |
|  <img width="357" alt="image" src="https://github.com/FRONTENDSCHOOL8/super-market/assets/148828856/ad4e6768-1a14-4657-b3fe-5552971ec419"> |
- 클래스명이 겹치지 않도록 구체적으로 클래스명 수정

fix(feat/kina/#79): main class명 수정

---

src/lib/components/clickBtnMoveToSite.js
src/lib/components/index.js
src/lib/components/validationInput.js
src/pages/login/index.html
src/pages/login/index.js
src/styles/pages/_login.scss

| 완성 이미지/GIF |
|![Animationd](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/576bc12a-e25c-4f75-a69b-054b2120a766)
- 로그인 페이지 아이디 및 비밀번호 각 조건에 맞게 입력 시 로그인 버튼 활성화
- 회원가입 버튼 클릭 시 회원가입 페이지로 이동
- /src/lib/components/ 경로 모듈 2개 추가
- validationInput.js : input 이벤트 유효성 검사를 할 수 있는 함수입니다. 첫 번째 인수는 셀렉터가 들어가고 두 번째 인수는 정규식이 들어갑니다. 예시) validationInput('#loginUserId', /^[A-Za-z0-9]{6,16}$/);
- clickBtnMoveToSite.js : 버튼이지만, 클릭 시 a 태그처럼 사이트로 이동시켜 주는 기능을 할 수 있는 함수입니다. 첫 번째 인수는 셀렉터가 들어가고 두 번째 인수는 경로가 들어갑니다. 예시) clickBtnMoveToSite('#login-register-button', '/src/pages/register/');

feat(feat/kim/#84): 로그인 페이지 로그인 버튼 활성화 기능 및 회원가입 버튼 기능 추가

---

src/pages/register/index.html
src/pages/register/index.js

| 완성 이미지/GIF |
|![Animationd2](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/a2ab1228-e2ea-40fe-a166-4eaa25ce9cde)|
- 회원가입 페이지 회원가입 기능 구현
필수 입력 필드만 구현되어 있어 추후 보완 예정

feat(feat/kim/#86):회원가입 페이지 회원가입 기능 구현

---

src/pages/products/index.html
src/pages/products/index.js
src/styles/pages/_products.scss

| 완성 이미지/GIF |
|![feat#91 product_by_category](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/e839d88a-311c-456e-9853-96943088bd53)|
- 카테고리 항목 선택 시 해당하는 목록만 나열하는 기능
- 검색된 총 건수를 표시하는 기능

feat(feat/sang/#91): 카테고리 별 목록 나열 기능 구현

---

src/pages/login/index.html
src/pages/login/index.js

| 완성 이미지/GIF |
|![Animationd1](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/37e1c6c6-8322-410f-8dc3-86496002bde6)|
- 로그인 기능 구현

feat(feat/kim/#93): 로그인 기능 구현

---

src/lib/components/productCard.js
src/pages/detail/index.html
src/pages/detail/index.js
src/styles/pages/_detail.scss

| 완성 이미지/GIF |
|---|
| <img width="876" alt="image" src="https://github.com/FRONTENDSCHOOL8/super-market/assets/148828856/04f1d241-c184-42ea-8890-6636cd4d2330"> ![image](https://github.com/FRONTENDSCHOOL8/super-market/assets/148828856/bbe19a0e-36c9-4c8a-9fbf-fece2ce9de98) |
|   |
- db의 data에 따라서 상품의 정보를 렌더링
- 상세설명 이미지

feat(feat/kina/#83): 디테일페이지 동적 렌더링

---

src/pages/cart/index.html
src/pages/cart/index.js
src/styles/pages/_cart.scss

| 완성 이미지/GIF |
|![feat#95  cart-productview](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/f374f963-a6f8-4527-bcc0-2890cf96c881)|
- 장바구니에 선택한 상품 데이터 출력하기
- 헤더의 메뉴에서 정상적으로 상품 목록으로 가도록 링크 수정

Feat/sang/#95: 장바구니 목록 데이터에서 받아와서 뿌리기

---

src/pages/detail/index.js
src/styles/pages/_detail.scss

| 완성 이미지/GIF |
| --- |
|  <img width="867" alt="Screenshot 2024-01-12 at 5 14 10 PM" src="https://github.com/FRONTENDSCHOOL8/super-market/assets/148828856/0067628b-6a74-4d79-9d28-dd410ffd3a72">  |
-할인율 및 실제 가격이 표시되지않았던 부분 마크업 수정 및 실제 data에 반영

Feat/kina/#100 디테일페이지 할인가격 표시 및 반영

---

src/lib/components/cartModal.js

| 완성 이미지/GIF |
| -------------- |
|        ![화면 기록 2024-01-12 오후 8 34 55](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/eb2b54af-fe39-44cd-ab5c-a99a39904b04)         |
- 장바구니 모달에서 상품 개수를 설정한 후 장바구니 담기를 클릭하면 데이터베이스에 담긴다.
- 이미 장바구니에 담긴 상품은 장바구니에 담긴 상품의 개수에 새로 담는 개수를 추가한다.

feat(feat/ryu/#104): 장바구니에 상품 담을 경우 데이터베이스로 이동

---

src/lib/components/index.js
src/lib/components/sliceNumberMaxLength.js
src/lib/components/validationInput.js
src/pages/register/index.html
src/pages/register/index.js
src/styles/pages/_register.scss

| 완성 이미지/GIF |
|![1](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/c795fa92-5d48-4298-bc9c-3d71d16171fe)
- 회원가입 시 성별, 생년월일 선택 입력 항목 및 선택 동의사항 체크 여부 데이터 통신으로 전달
- 생년월일 유효성 검사
- 아이디 생성 시 cart 생성 후 cart_id까지 생성한 users 데이터에 연결

feat(feat/kim/#97): 회원가입 페이지 기능 추가

---

src/lib/components/header.js
src/pages/cart/index.html
src/pages/cart/index.js
src/styles/pages/_cart.scss

| 완성 이미지/GIF |
|![feat#107 calculate-price](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/e9a70eac-af48-4926-a468-fcfa84a8768c)|
- '선택 삭제' 클릭 시 선택된 상품 장바구니에서 삭제
- 장바구니에 상품이 없을 경우 및 선택된 상품이 없을 경우 주문하기 버튼 비활성
- 배송비는 선택된 상품 금액의 합이 43,000원 이상일 경우 0원
- 적립은 결제 예정 금액의 0.1%
- 로그인하지 않은 상태에서 페이지 진입 시 로그인 화면으로 이동
- 상품 수량 조절 및 선택상태와 조절에 따라 결제금액 계산
- 목록 로딩 시 스켈레톤 ui를 적용했으나.. 5초이상 걸려서 느려보이는건 마찬가지라서 고민..

Feat/sang/#107: 상품 수량 조절 및 가격 계산, 삭제 기능 및 스켈레톤 UI 적용

---

src/pages/cart/index.html
src/pages/products/index.html
src/pages/products/index.js
src/styles/pages/_products.scss

| 완성 이미지/GIF |
|![feat#116 product-sort](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/50074035-bae8-4667-a4b9-26738b0dd3c0)|
- 상품 분류 - 브랜드 X
- 상품 분류 - 가격
- 상품 분류 - 혜택 (할인 여부)
- 상품 분류 - 유형
- 상품 분류 - 특정 상품 제외 X
- 상품 정렬 - 추천순(리뷰 보유 순)
- 상품 정렬 - 신상품순
- 상품 정렬 - 판매량순
- 상품 정렬 - 혜택순
- 상품 정렬 - 낮은가격순
- 상품 정렬 - 높은가격순

Feat/sang/#116: 상품 분류 및 정렬 기능 구현

---

src/pages/login/index.html
src/pages/register/index.html
src/pages/register/index.js

| 완성 이미지/GIF |
|![중복](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/954311cf-89d9-4d31-854f-3c07f36742e1)|
- 로그인 또는 이메일 입력란 공백인 상태에서 중복확인 버튼 누를 시 "OOO을 입력해 주세요" 문구 출력
- 회원가입 및 로그인 페이지 수정된 헤더 적용

modify(feat/kim/#122): 로그인, 이메일 중복확인 기능 보완 및 수정된 헤더 적용

---

src/lib/components/productCard.js
src/pages/cart/index.js
src/pages/products/index.html
src/pages/products/index.js
src/styles/layout/_header.scss
src/styles/pages/_products.scss

| 완성 이미지/GIF |
|![feat#121 pagination-cart](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/f9d86903-1e39-49f2-b32b-4d651d9debcb)|
- 장바구니 담기 - 경혜님 작업 분 라이브러리 함수 호출
- 페이지네이션 작업

Feat/sang/#121: 상품목록 페이지의 페이지네이션 기능 및 장바구니 담기 기능

---

index.html
src/lib/components/header.js
src/pages/login/index.html
src/pages/mypage/index.html
src/pages/mypage/index.js
src/pages/products/index.html
src/styles/layout/_header.scss
src/styles/pages/_index.scss
src/styles/pages/_mypage.scss
vite.config.js

| 완성 이미지/GIF |
|![feat#126 header-mypage](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/4db4b5b3-c2a2-499e-98cd-3d965bef9d66)|
- 로그인한 사용자의 이름 표시
- 로그아웃 버튼 표시
- 로그아웃 기능
- 마이페이지 이동 링크 표시
- 마이페이지 마크업 및 스타일링
- 본 pr이 merge된 이후 products/index.html 의 헤더 복사 붙여넣기가 필요합니다.

Feat/sang/#126: 헤더의 로그인 상태 제어 및 마이페이지

---

src/pages/register/index.html
src/pages/register/index.js
src/styles/pages/_register.scss

| 완성 이미지/GIF |
|![ani](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/a277342f-7f33-48e9-a452-17baf3e01c83)|
- 친구초대 추천인 아이디 체크박스 클릭 시 입력란 마크업 및 스타일링
- 데이터 통신 통해 입력한 추천인 아이디 존재 여부 확인 기능 추가
- 참여 이벤트명 체크박스 클릭 시 입력란 마크업 및 스타일링

feat(feat/kim/#125): 추가입력 사항(친구초대 추천인 아이디, 참여 이벤트명) 클릭 시 요소 추가

---

src/pages/cart/index.html
src/pages/cart/index.js
src/pages/login/index.js
src/pages/mypage/index.js
src/styles/layout/_header.scss
src/styles/pages/_cart.scss

| 완성 이미지/GIF |
|![feat#130 modify-cart](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/0c9c378a-9621-4cde-9538-08f538399c81)|
- 마이페이지, 로그인, 장바구니의 최상단 await 호출 제거
- 주문 완료 시 팝업의 디자인 디테일 작업

Feat/sang/#130: 디자인 디테일 작업 및 빌드 불가 문제 수정

---

src/lib/components/header.js
src/pages/address/index.html
src/pages/cart/index.html
src/pages/products/index.html

| 완성 이미지/GIF |
|헤더 최신화|
- 상품목록의 헤더 최신화
- 장바구니의 헤더 최신화
- 주소검색창의 헤더 최신화

modify(feat/sang/#136): 헤더 최신화

---

src/pages/login/index.html
src/pages/mypage/index.html
src/pages/mypage/index.js
src/pages/register/index.html

| 완성 이미지/GIF |
|![ani](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/ec693616-59b9-49f2-8e27-494cca2b14fe)|
- 회원가입, 로그인, 마이 페이지 마크업 수정 및 회원탈퇴 기능 추가
- 회원가입 페이지 validator 에러 수정
- 회원가입/로그인/마이페이지 헤드, 헤더 영역 수정
- 마이페이지 회원탈퇴 기능 추가

feat(feat/kim/#137): 회원가입, 로그인, 마이 페이지 마크업 수정 및 회원탈퇴 기능 추가

---

src/pages/detail/index.html
src/pages/detail/index.js
src/styles/pages/_detail.scss

| 완성 이미지/GIF |
| ![gnrl](https://github.com/FRONTENDSCHOOL8/super-market/assets/148828856/08e1e3e8-40e2-4d27-a816-dbe0b4ba2784) |
- 후기 작성하기 버튼을 클릭하면 후기를 작성할수 있는 창을 dialog로 구현
- 작성한 내용을 pocketbase의 create를 이용해 전달
- record의 list를 가져와서 렌더링
- user_id에 있는 name을 expand로 가져와서 마스킹된 이름으로 보여줌
- 작성한 순으로 sorting

Feat/kina/#127 후기 작성하기 및 보여주기 구현

---

src/pages/register/index.html
src/pages/register/index.js
src/styles/pages/_register.scss

| 완성 이미지/GIF |
|인증번호 기능|
|![인증번호](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/b29aa21b-2bea-46cb-be5a-71fef63bb8d9)|
|인증번호 확인 없이 가입 요청 시 인증번호 확인 유도 문구 출력|
|![인증번호2](https://github.com/FRONTENDSCHOOL8/super-market/assets/145115283/373f79e9-bedb-4ba3-addb-baf56875e210)|
- 회원가입 페이지 인증번호 기능 구현
- 인증번호 호출 후 아무런 값 입력 없이 인증확인 클릭 시 에러 문구 출력
- 인증번호 확인 검증 없이 회원가입 진행 시 인증확인 유도 문구 출력
- 인증확인 시 스타일링 및 disabled 적용 (입력값 지울 경우 인증확인 재진행 필요)

feat(feat/kim/#144): 회원가입 페이지 인증번호 기능 구현

---

src/pages/detail/index.html
src/pages/detail/index.js
src/styles/pages/_detail.scss

- 가격 부분 스타일링이 제대로 적용되지 않아 마크업 수정
- detail_img 가 렌더링 되지않던 부분 js 수정

modify(feat/kina/#147):  제대로 보이지 않던 부분 수정

---

src/pages/cart/index.js
src/styles/components/_recentBar.scss
src/styles/pages/_main.scss

| 완성 이미지/GIF |
|![image](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/12069572-1d22-4c2e-850a-2a43aee9349d)|
- 장바구니 페이지 경로 수정
- 최근 본 상품 및 메인페이지 스와이퍼 화살표 이미지 경로 수정

modify(feat/sang/#150): 이미지 경로 배포 기준으로 표시가능하도록 수정

---

index.html
src/pages/benefit/index.html
src/pages/benefit/index.js
src/styles/components/_productCard.scss
src/styles/components/_recentBar.scss

| 완성 이미지/GIF |
|         ![화면 기록 2024-01-15 오후 6 07 38](https://github.com/FRONTENDSCHOOL8/super-market/assets/91606951/eb7c22a5-78dd-4db4-948d-05c69057e206)        |
- 상품 호버 시 이미지 확대
- 메인 페이지 광고 팝업 클릭 시 헤어/바디/구강 상품 목록으로 이동
- 메인 페이지 배너, 라인배너 클릭 시 특가/혜택 페이지로 이동
- 최근 본 상품 스타일 수정

Feat/ryu/#138: 마이크로 애니메이션 및 이동 링크 추가

---

src/pages/detail/index.html

| 완성 이미지/GIF |
|![image](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/1f9d2e68-4f87-411e-8e4c-f6af59706cf2)|
- 상품 디테일 페이지 로그인 이후 헤더 수정

modify(feat/sang/#154): 상품 디테일 페이지 헤더 수정

---

src/lib/components/cartModal.js

| 완성 이미지/GIF |
| --- |
| <img width="815" alt="Screenshot 2024-01-15 at 11 10 15 PM" src="https://github.com/FRONTENDSCHOOL8/super-market/assets/148828856/05fa36d9-5452-4a36-b0dc-94b5c5116f0d"> |
- 경혜님이 만들어둔 component에서 매개변수를 추가하여 카운트 되도록 수정

feat(feat/kina/#156): 경혜님 코드로 디테일페이지에서 장바구니 카운트 추가

---

src/pages/mypage/index.html
src/pages/mypage/index.js
src/styles/pages/_mypage.scss

| 완성 이미지/GIF |
|![image](https://github.com/FRONTENDSCHOOL8/super-market/assets/46062634/05bc3618-9113-4f58-a3aa-11a42783d21e)|
- 폼 컨트롤 span에서 label로 변경
- 유저의 기본 데이터 정보 세팅

modify(feat/sang/#159): span 태그 label로 변경, 기본 유저 데이터 세팅
